### ISSUE TITLE
Issue with Encoded Edits

### ISSUE THREAD

**Issue by danjohnso** [NicolasCARPi/jquery_jeditable#110]
Lines 173-175 of jquery.jeditable.js:
self.editing    = true;
self.revert     = $(self).html();
$(self).html('');

When your text is an encodable character (ie &), then the form element gets set to the encoded value (&amp; instead of just &) which isn't very user friendly, especially since if you save the value back it changes the value.  I changed it to this and have not seen any adverse side effect:

self.revert     = $(self).text();

**Comment by NicolasCARPi** [comment]
Hello, thanks for your contribution. Your change has been incorporated in the code :)
