### ISSUE TITLE
Holy Pull Rrequest!

### ISSUE THREAD

**Issue by trans** [NicolasCARPi/jquery_jeditable#114]
30 open pull requests!? Anyone at the helm of this project anymore?

**Comment by kashifshamaz21** [comment]
Yes, looks like there isn't any active maintainence going on for this library. How do we keep it alive? Any takers to take it over, people who have forked off from this and are actively maintaining their versions.
@tuupola thoughts please..

**Comment by NicolasCARPi** [comment]
Hello,

I'm the new maintainer of this project. So the answer is YES THIS IS STILL MAINTAINED \o/ :)
