### ISSUE TITLE
Handling of dynamic form fields

### ISSUE THREAD

**Issue by email2vimalraj** [NicolasCARPi/jquery_jeditable#118]
I'm having a trouble in using while I've dynamic form fields in my code.

Example: I've a relationship select tag where Father, Mother and Others are options. If I select Others, I should get a new input box for the user to specify the other relationship.

I tried using jQuery change method for select tag, but nothing happens.

**Comment by NicolasCARPi** [comment]
You should add the .editable to the element after its creation.
