### ISSUE TITLE
inline width/height saving workaround, doesn't work around

### ISSUE THREAD

**Issue by huehnerhose** [NicolasCARPi/jquery_jeditable#134]
I use the plugin the first time, so maybe I'm just don't getting it ;)

I do not set any width or height on my elements or input fields and use spans as "source"-elements for jeditable. First click and edit everything works perfectly. Second edit-attempt I don't see any input field (width:0; height: 0)

On line 113 I saw:

``` javascript
/* inlined block elements lose their width and height after first edit */
/* save them for later use as workaround */
var savedwidth  = $(self).width();
var savedheight = $(self).height();
```

I think this didn't work, my workaround workaround looks like:

``` javascript
            if($(self).width() !== 0){
              var savedwidth  = $(self).width();
            }

            if($(self).height() !== 0){
              var savedheight = $(self).height();
            }

```

And works here. Maybe there is a much more elegant way :)

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for your contribution. This code has been removed :)

Regards,
~Nico
