### ISSUE TITLE
Does not work with jQuery 2.1.1

### ISSUE THREAD

**Issue by lukeenglish** [NicolasCARPi/jquery_jeditable#135]
As of jQuery 2.1.1 (latest version) async:false is depreciated when executing ajax on the main thread. 

May I suggest the code been altered to either allow running of the ajax loading syncrously, and do the revelent updates in a callback function, or set the ajax call to run on a seperate thread. 

![capture](https://cloud.githubusercontent.com/assets/1931447/4406267/a3944c12-44c1-11e4-88b3-31419b1f5fb4.PNG)

**Comment by NicolasCARPi** [comment]
Hello,

async has been removed. Thanks for your contribution :)

Next version will work fully with latest jquery.

~Nico
