### ISSUE TITLE
Using onblur: 'submit' with cancel button causes form to submit

### ISSUE THREAD

**Issue by andyface** [NicolasCARPi/jquery_jeditable#136]
Having the onblur option set to submit and also having the cancel button setup causes odd behaviour. When clicking the cancel button, the form submits. I think this is because by clicking the cancel button, it is triggering blur on the input, which would be expected in this situation, however, because the form is being submitted on blur this action is being triggered along with the cancel action, which causes unexpected results.

Please see a reduced test case below:
http://jsfiddle.net/andyface/qogyft8q/

**Comment by NicolasCARPi** [comment]
Hello,

This behavior doesn't exist anymore. Thanks for your contribution!
