### ISSUE TITLE
bower.json file has no main section

### ISSUE THREAD

**Issue by andreyfomin** [NicolasCARPi/jquery_jeditable#138]
bower configuration file bower.json has no section main. Example "main": "jquery.jeditable.js"

Thus I can't build my application with brunch tool. It doesn't copy  "jquery.jeditable.js" to my application.

I think this issue is very important no one can use automatic build process to copy js file to the web application!!

**Comment by NicolasCARPi** [comment]
Hello,

I'm the new maintainer of this project. You can expect to find it on npm soon with 1.8.0.

Regards,
~Nico
