### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by dandv** [NicolasCARPi/jquery_jeditable#139]
See #114

**Comment by kashifshamaz21** [comment]
Yes, looks like there isn't any active maintainence going on for this library. How do we keep it alive? Any takers to take it over, people who have forked off from this and are actively maintaining their versions.
@tuupola thoughts please..

**Comment by mayacr86** [comment]
Hey! is there any other particular fork that is indeed active that you guys could recommend? I really like this plugin :(

Tough I'm having some issue with [x-editable](http://vitalets.github.io/x-editable/docs.html) since both initialize the same way...

**Comment by NicolasCARPi** [comment]
Hello,

I'm the new maintainer of this project. So the answer is YES THIS IS STILL MAINTAINED \o/ :)
