### ISSUE TITLE
onBlur function should support a return value to allow for normal cancellation

### ISSUE THREAD

**Issue by twig** [NicolasCARPi/jquery_jeditable#14]
I've noticed that if I define an onBlur function, it will run that function but leave the form intact without "cancelling".

It would be nice if we were able to return "true" to maintain this "halt the cancellation" behaviour, but return false to keep the standard behavior (if no onBlur is defined)

This way, people can keep track of both "on cancel" and "on submit" events.

**Comment by NicolasCARPi** [comment]
Hello,

I have implemented this feature :) Thanks for the suggestion!

~Nico
