### ISSUE TITLE
Comparison with x-editable

### ISSUE THREAD

**Issue by dandv** [NicolasCARPi/jquery_jeditable#140]
How does this compare with @vitalets [x-editable](https://github.com/vitalets/x-editable)?

**Comment by thezoggy** [comment]
x-editable looks like its stalled development awhile ago, and while it does have some nice feature you can see that the minified vs non minified versions are not kept in sync.. and 'dev' has been in limbo for 2+ years trying to get a minor revision out.

**Comment by NicolasCARPi** [comment]
At least now jeditable is maintained :)
