### ISSUE TITLE
missing cow.jpg

### ISSUE THREAD

**Issue by tamarmot** [NicolasCARPi/jquery_jeditable#141]
My code does css validation as part of the build, and the file 'jeditable/tests/data/cow.jpg' is not part of your repository, though it is referenced by jeditable/tests/testsuite.css

thanks

**Comment by NicolasCARPi** [comment]
Hello,

I'm the new maintainer of this repository. The next version will probably not include the same tests and css. I've removed the cow.jpg reference anyway.

Thank you for your contribution :)

~Nico
