### ISSUE TITLE
issue with x-editable

### ISSUE THREAD

**Issue by mayacr86** [NicolasCARPi/jquery_jeditable#142]
Well.. seems like you can use one or the other. Both plugins initialize with '.editable()':

```
$('#username').editable();
```

Is there a way to rename the function for your plugin as .jeditable() instead? Since [x-editable](http://vitalets.github.io/x-editable/docs.html) uses the same name.

**Comment by solsticesurfer** [comment]
You can change the name for jeditable by going through each of the source files (e.g. jquery.jeditable.js) and changing all references to $.editable and $.fn.editable to something else. I would suggest renaming them to $.jeditable and $.fn.jeditable respectively.

**Comment by mayacr86** [comment]
Nice! Thanks, I'll do that :)

**Comment by NicolasCARPi** [comment]
Hello,

I'm the new maintainer of this project.

Closing this because changing the name of the init function would break too much people's code ;)

~Nico
