### ISSUE TITLE
 editor specific browser-compability issue, including the <p> tag or <div> tag instead of <br>

### ISSUE THREAD

**Issue by prasanthprem** [NicolasCARPi/jquery_jeditable#143]
Normally when we type a sentence in an wysiwyg editor and if we need one in next line we use to press the enter key and it will automatically insert a `<br>` tag. But when we use the jeditable wysiwyg editor and do this it is inserting `<p></p>` tags instead of `<br>` in internet explorer and `<div></div>` tag in chrome. But it is inserting `<br>` tag in mozilla(which is the right one)
So I smell this as an editor specific browser-compability issue
Please fix this.

**Comment by kenorb** [comment]
This happens on demo at http://www.appelsiini.net/projects/jeditable/wysiwyg/wysiwyg.html

**Comment by tuupola** [comment]
The example uses quite old jWYSIWYG plugin.  Have you tried with the latest version?

https://github.com/akzhan/jwysiwyg/

**Comment by kenorb** [comment]
Related: https://code.google.com/p/jwysiwyg/issues/detail?id=15

**Comment by NicolasCARPi** [comment]
Closing because jwysiwyg is dead anyway.
