### ISSUE TITLE
Double balise for 'submit' in  $.fn.editable.defaults cause double send of the form

### ISSUE THREAD

**Issue by SylvainPeigne** [NicolasCARPi/jquery_jeditable#144]
When we enter as option something like :

~~~html
submit: '<br/><button class="btn btn-success" type="submit" >Ok</button>',
~~~

The form is ajaxed two times.

When we delete the `<br/>`, everthing work fine.

**Comment by NicolasCARPi** [comment]
Hello,

I cannot reproduce the behavior you describe. You can use the `submitcssclass` option to style your buttons (not yet released feature!). See [demo](https://jeditable.elabftw.net) for example of button styling.
