### ISSUE TITLE
Feature suggestion - allow the save url to fail/error and trigger either built in or callback function 

### ISSUE THREAD

**Issue by nneul** [NicolasCARPi/jquery_jeditable#147]
Idea would be to allow inline editing, but to easily allow validation as well - i.e. server refused to accept that particular update.

Built-in/default behavior could be something as simple as flashing the input area and leaving it in an editable state.

**Comment by NicolasCARPi** [comment]
Hello,

You can use the different functions to do that. See the demo for examples.
