### ISSUE TITLE
PUT should have option to override type

### ISSUE THREAD

**Issue by atourkow** [NicolasCARPi/jquery_jeditable#148]
According to http://www.appelsiini.net/2008/put-support-for-jeditable PUT functionality was added for REST, but it says _Jeditable does it Rails way by using POST method but submitting additional variable called _method with value put._   

However, my REST API is looking for the PUT header and Chrome supports it (the only browser I need to support, as it's an admin page) 

Can you please make it so PUT can also override the type?

**Comment by NicolasCARPi** [comment]
PUT method will probably not be supported in this project. I'm reducing the feature set to make this project maintainable, and we'll stick to GET and POST only to keep it simple :)
