### ISSUE TITLE
Html text as value on input

### ISSUE THREAD

**Issue by paulodiogo** [NicolasCARPi/jquery_jeditable#149]
When I have one link inside an element, the plugin behave as following in link:

http://jsfiddle.net/paulodiogo/5h5rm4z9/

Do you guys have any idea how to solve this? 

PS. I'm using this because of 'jquery-datatables-editable', its use the plugin in a <td> and I have a structure like on example.

**Comment by nickleus** [comment]
@paulodiogo what's the "one link inside an element" u refer to? your fiddle demonstrates making a field editable by clicking a button--what was the expected result? what's the issue, exactly?

**Comment by paulodiogo** [comment]
@nickleus I'm sorry, the correct example is: http://jsfiddle.net/paulodiogo/5h5rm4z9/3/

**Comment by NicolasCARPi** [comment]
get the A out of the div! ;)
