### ISSUE TITLE
Css class for Select tag.

### ISSUE THREAD

**Issue by cescoferraro** [NicolasCARPi/jquery_jeditable#150]
Any solution for [this](http://stackoverflow.com/questions/3477829/style-the-select-list-element-in-jeditable)?
I want to bootstrap style the select inside the form, but with no sucess on 1.7.3. Any tip?

**Comment by NicolasCARPi** [comment]
This will probably be solved by https://github.com/NicolasCARPi/jquery_jeditable/pull/132

**Comment by NicolasCARPi** [comment]
Code is merged. Use "cssclass" option.
