### ISSUE TITLE
not working on dynamically generated table

### ISSUE THREAD

**Issue by spyshow** [NicolasCARPi/jquery_jeditable#156]
hi 
i have a table with the row are generated by a script. after i generate them i call the jquery selector for jeditable but nothing happens ... if i put a static row , the script work ... it's not working only in the generated rows

**Comment by spyshow** [comment]
any help here please !!!

**Comment by gangadharjannu** [comment]
Could you provide a working copy like jsfiddle or jsbin to look into?

**Comment by NicolasCARPi** [comment]
Hello, this is due to the way jeditable is written. Something I'm willing to fix down the road. Right now the workaround is to retrigger the jeditable on the element after it appeared.
