### ISSUE TITLE
request: add onEdit event

### ISSUE THREAD

**Issue by twig** [NicolasCARPi/jquery_jeditable#16]
I would like to request an "onEdit" event.

This would make it easier for people to detect when an edit event has begun, allowing them to fully customise the text prior to editing.

This will help solve your "please strip markup", newline or formatting issues and allow for some more customisation to jEditable.

It should be a small tweak to the code block which checks if it is an Ajax load.

a) stores the original element html() somewhere
b) retrieves the ajax content from "loadurl"
c) puts it into the element for editing

altered:
a) stores the original element html() somewhere
b) passes the original html to "onEdit" handler
c) retrieve the output and store the same way the ajax content is saved
d) puts it into the element for editing

**Comment by NicolasCARPi** [comment]
Hello,

onedit exists now! You also have before.
