### ISSUE TITLE
recovering live demo please?

### ISSUE THREAD

**Issue by oonid** [NicolasCARPi/jquery_jeditable#160]
hi,
thank you for starting new maintenance process of this app.
would you please recover the live demo?
or may be there's a new live demo URL?
thank you.

**Comment by NicolasCARPi** [comment]
Hello,

Yes for now the demo is in the repo. There is no live demo atm but as soon as I'm satisfied with the demo page I'll put it up (maybe a github page would be the easiest solution).

**Comment by NicolasCARPi** [comment]
Live demo is here: https://jeditable.elabftw.net/ :)
