### ISSUE TITLE
Register at CDN to increase ease of deployment

### ISSUE THREAD

**Issue by holtkamp** [NicolasCARPi/jquery_jeditable#161]
To stimulate adoption and increase ease of deployment during production, registration of the dist files at a CDN like http://www.cdnjs.com is useful.

Will try to submit it to http://www.cdnjs.com and report back here 👍 

(steps are documented in a similar issue here: https://github.com/onokumus/twbuttons/issues/1)

**Comment by thezoggy** [comment]
1.7.3 is already at cdnjs, I'll send in update for 1.8.0

**Comment by holtkamp** [comment]
Great, now sit back and wait patiently for `1.8.0` to appear on https://cdnjs.com/libraries/jeditable.js

**Comment by NicolasCARPi** [comment]
Ok, just realized that I wasn't following this repo… -_-' I'm just seeing this now.

@thezoggy thanks for taking care of the cdnjs stuff. Let me know if you need some help!

**Comment by holtkamp** [comment]
Yeah, respect for @thezoggy for his effort and patience, the CDNJS team has a clear view on the expected quality, but this delays quite a bit. I will light and 🕯 and hope for the best 😄

**Comment by thezoggy** [comment]
I re-based and resubmitted with their requested changes just now.. its painful to work with the cdnjs repo with only 16gb of ram :(
One of their bots told me to do the auto update using npm the other says git.. I left it for npm since thats what their wiki says they prefer.

**Comment by NicolasCARPi** [comment]
Cheers :clap:

**Comment by thezoggy** [comment]
2.0.2 is now on cdnjs.
