### ISSUE TITLE
OnSubmit "Spinner" and Check if Server Returned Error Do Not Hide the Edit

### ISSUE THREAD

**Issue by tetrahydra** [NicolasCARPi/jquery_jeditable#162]
Hello

I would like to know how can I achieve this:

1. When clicked save, show "spinner" icon.

2. After submitted to the server and wait for the ajax return (OK or ERROR), if error, then do not hide the edit input/textarea.

**Comment by NicolasCARPi** [comment]
Hello,

You can maybe use the 'onsubmit', 'before' or 'callback' options to run what you want when you want ;)

See [the Complete example on the demo](https://jeditable.elabftw.net/) source code.
