### ISSUE TITLE
options.type as 'number' and options.width bug

### ISSUE THREAD

**Issue by Romchik** [NicolasCARPi/jquery_jeditable#163]
## how to reproduce
```
$(el).editable(url, {
    type: 'number',
    width: 50
});
```

## expected result
`<input type="number" style="width:50px">`
## actual result
`<input type="number" style="width:0">`

**Comment by NicolasCARPi** [comment]
Hello @Romchik,

Thank you for reporting this issue. I have fixed it, you will find the working code in the next version, or already on the master branch. You can also patch the code manually in the mean time (see commit above, it's three lines).

Cheers,
~Nico
