### ISSUE TITLE
New records

### ISSUE THREAD

**Issue by wings77** [NicolasCARPi/jquery_jeditable#164]
Is it possible to take an empty table and add new records?

**Comment by NicolasCARPi** [comment]
Hello,

Not sure I understand your question. Would you mind explaining clearly what you want to achieve?

**Comment by wings77** [comment]
ok, my question is about entering new records to the table, not just editing them.

**Comment by NicolasCARPi** [comment]
> the table

Which table are you talking about? Maybe provide code examples because it's still very vague.

**Comment by wings77** [comment]
mas claro imposible, buscare la respuesta en el código fuente, veo que es un buen plugin pero necesito que tenga esta característica. Gracias por tu repuesta.

**Comment by NicolasCARPi** [comment]
de nada…
