### ISSUE TITLE
documentation for creating new input types

### ISSUE THREAD

**Issue by eman1986** [NicolasCARPi/jquery_jeditable#165]
I need a date time picker that _doesn't_ use jquery-ui so I'm making my own based off what existing plugins are already written, though a documentation on what each function did would be a great help and could help spawn new plugins for this great library

**Comment by NicolasCARPi** [comment]
Hello,

Yes you're right, it's a good idea!

**Comment by NicolasCARPi** [comment]
If it hasn't happened in two years, it probably never will. Closing.
