### ISSUE TITLE
POST Json Data via Ajax

### ISSUE THREAD

**Issue by NLI-KelbyHunt** [NicolasCARPi/jquery_jeditable#168]
# Description
When I add **ajaxoptions** and content type of `application/json`, I see the values sent in the body of the request but they are not in Json format. ASP controllers are picky and I cannot get this to bind to parameters `value=testvalue&id=1` Is there a way to JSON.stringify the POST data? I just want the id/value to be converted to JSON string before sending it while still picking up those values automatically from the HTML element.

Unrelated question, can you use Glyph Icons/Font Icons as the button text with bootstrap classes?

## how to reproduce

```js
$("table > tbody td > div.cronExpression").editable("@Url.Action(nameof(AdministrationController.EditCronExpression))", {
            ajaxoptions: {
                contentType: "application/json"
            },
            cancel: "Cancel",
            cancelcssclass: "btn btn-secondary",
            submit: "Save",
            submitcssclass: "btn btn-success",
            callback: function() {
                window.location.reload();
            }
        });
```

I have attempted a couple things:
```js
submitdata: function (revert, settings, submitdata) {
                return JSON.stringify(submitdata);
            }
```

```js
ajaxoptions: {
                contentType: "application/json",
                data: function(params) {
                    return JSON.stringify(params);
                }
            },
```

## expected result

`{"value":"testvalue", "id":1}`

## actual result

`value=testvalue&id=1`

# Environment

Browser: Chrome
OS: Windows

**Comment by NicolasCARPi** [comment]
Hello,

> Is there a way to JSON.stringify the POST data?

Why don't you put the target as a JS function? This way you do whatever you want to the data before sending it! ;)

> can you use Glyph Icons/Font Icons as the button text with bootstrap classes?

Didn't try it.

**Comment by NLI-KelbyHunt** [comment]
> Why don't you put the target as a JS function? This way you do whatever you want to the data before sending it! ;)
Don't know why I didn't think of that, I'll write a PreProcess function. Thanks @NicolasCARPi
