### ISSUE TITLE
default tooltip wording changes based on event

### ISSUE THREAD

**Issue by thezoggy** [NicolasCARPi/jquery_jeditable#170]
right now `Click to edit` is what is used. Which works as the default with no event set. But if you do event: dblclick.. then its technically wrong. I suggest to apply logic on backend to make the default text `Double click to edit` if the event dblclick is used.. but feel free to push back and just tell people to set the tooltip option since they are setting the event option anyways.

**Comment by NicolasCARPi** [comment]
Hello,

You make a valid point. But I'll take the lazy road and «just tell people to set the tooltip option since they are setting the event option anyways.» :)

Regards,
~Nico
