### ISSUE TITLE
2.0.1 -- inputcssclass not working

### ISSUE THREAD

**Issue by thezoggy** [NicolasCARPi/jquery_jeditable#171]
setting inputcssclass does not work in 2.0.1. (actually looks like it was broke when you took over, 1.8.0+)
Works fine in 1.7.3.

**Comment by thezoggy** [comment]
example: http://jsfiddle.net/L8a12den/

**Comment by thezoggy** [comment]
also to note, you never 'released' the 2.0.2 version on git, so cdnjs only goes upto 2.0.1

**Comment by NicolasCARPi** [comment]
Hello,

First, I released 2.0.2 on github, thanks for telling me.

Second, the option `inputcssclass` doesn't seem to exist in the source code, in latest version or 1.7.3 I don't find the string `inputcssclass`, so I'm not sure why you think this option exists.

`cssclass` will be applied to the `form` element and works as expected as you can see in [the demo](https://jeditable.elabftw.net).

**Comment by NicolasCARPi** [comment]
> digging into my 1.7.3, it looks like I had a forked version which had some updates/pulls..

Ok that makes sense :)

I think instead of adding yet another option it's better to use css selectors as you suggested. But if you make a PR with that code I'll accept it ;)

**Comment by thezoggy** [comment]
ok i'll submit it
