### ISSUE TITLE
Add feature to allow pressing ESC to cancel edit

### ISSUE THREAD

**Issue by elixom** [NicolasCARPi/jquery_jeditable#177]
# Description
Allow pressing ESC to cancel edit

## how to reproduce
Edit a text
Press ESC

## expected result
Cancels edit

## actual result
Nothing happens

# Environment
Browser: Chrome
OS: Windows 8
jQuery 1.11.1

**Comment by NicolasCARPi** [comment]
Hello,

This is working with Firefox on GNU+Linux but not with other browsers or operating systems.

I'll try and add this ;)

**Comment by thezoggy** [comment]
```
	.bind( 'keydown' + namespace, function( event ) {
				// cancel on ESC
				if ( event.which === 27 ) {
					return false;
				}
	})
```

**Comment by NicolasCARPi** [comment]
@thezoggy would you mind making a pull request?

**Comment by thezoggy** [comment]
actually i see the code is already there, just needs slight updating. ill submit in a sec
