### ISSUE TITLE
One button to edit multiple input fields

### ISSUE THREAD

**Issue by TiagoDeSousa** [NicolasCARPi/jquery_jeditable#180]
Is there a way to have a button that when clicked enables multiple items to be edited at the same time instead of individually? The idea is to have a form with multiple fields and an Edit Form button on top that when clicked makes all the form items editable. 

Thank you.

**Comment by NicolasCARPi** [comment]
Hello,

One way to do it:

https://codepen.io/nicolascarpi/pen/KBWeJK

Clicking the button will make all the elements of class editable editable.
