### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by cfoellmann** [NicolasCARPi/jquery_jeditable#181]
# Description
when requiring the package via npm the config file is wrong.

you set `"main": "jquery.jeditable.js",` in https://github.com/NicolasCARPi/jquery_jeditable/blob/master/package.json#L5
That does not exist.

You need to set it to `"main": "dist/jquery.jeditable.min.js",` so the package can be found by npm based tools

**Comment by NicolasCARPi** [comment]
Hello,

Thanks for spotting and reporting the issue. I'm wondering if it should not rather be `"main": "src/jquery.jeditable.js",`? (non minified version)

**Comment by cfoellmann** [comment]
I am not an npm expert so I am not sure which one is "right". You might be right and using the non-minified version is better and can be minified by a process by the user later.

**Comment by cfoellmann** [comment]
great. thanks for solving this so fast. 👍

**Comment by NicolasCARPi** [comment]
Yes, I published a new version too! (2.0.6)

**Comment by cfoellmann** [comment]
when is the npm reference updated? Do you know that?

**Comment by NicolasCARPi** [comment]
I've just pushed to npm. It is now live.

**Comment by cfoellmann** [comment]
thanks again.
Are there no webhooks for github? for example packagist provides them for github repos

**Comment by NicolasCARPi** [comment]
Yes, there are webhook that could do that probably. I can also just remember to type "npm publish" after tagging a release :p
