### ISSUE TITLE
Method put doesn't work in Safari

### ISSUE THREAD

**Issue by sluchznak** [NicolasCARPi/jquery_jeditable#183]
# Description
I set "method" option as "put", but Safari sent POST request
## how to reproduce

```js
$(document).ready(function() {
  $('.editable').editable('/handler', {
    method: 'put',
    cancel: 'Cancel',
    submit: 'Update'
  });
});
```

## expected result

Request in Safari with PUT method

## actual result

Request in Safari with POST method

# Environment

Browser: Safari 12
OS: macos Mojave

**Comment by NicolasCARPi** [comment]
Why do you think [this template](https://github.com/NicolasCARPi/jquery_jeditable/blob/master/.github/ISSUE_TEMPLATE.md) is here?

**Comment by NicolasCARPi** [comment]
And you only see this behavior with Safari?

Which version of jquery are you using?

**Comment by NicolasCARPi** [comment]
Closing for lack of feedback.
