### ISSUE TITLE
Your Demo site has a 502 error it isn't working. Just letting you know. 

### ISSUE THREAD

**Issue by redbonzai** [NicolasCARPi/jquery_jeditable#185]
# Description

## how to reproduce

(add a jsfiddle/codepen example)

## actual result

# Environment

Browser:
OS:

**Comment by NicolasCARPi** [comment]
Hey thanks,

It's weird because I received an email saying it was 502, then went to check it and it was fine… And now it's down… Anyway, it's up now :)
