### ISSUE TITLE
How to set multiple options as selected?

### ISSUE THREAD

**Issue by eyleron** [NicolasCARPi/jquery_jeditable#186]
# Description
I can't get multiple <option> to be selected. None of the multiple select examples show clicking on the editable that already has e.g. "E" and "F" selected, generating a form field with both of those items selected.

## Expected result
With multiple "selected" keys, or one "selected" key with a value of an array of keys that should be selected, the <select> should show those multiple items as selected.

## Actual result
Using an array, none of the items are selected. I can only set one item to be selected.

# Environment
jQuery version: 3.3.1
Browser: Chrome 70
OS: Windows 10

**Comment by NicolasCARPi** [comment]
Hello,

Thanks for reporting this issue. I agree with you that multiple select should be possible. I'll have a look but don't get your hopes up, I'm maintaining this library, not really adding features. PRs are welcome.

Regards,
~Nico

**Comment by manfred-bamberger** [comment]
quick and dirty:

1/ selected = 'selection1'
2/ selected = '["selection1","selection2"]
tested with option loadurl, NOT tested with data option       

                 if (key !== 'selected') {
                            option = $('<option />').val(key).append(value);

                            // add the selected prop if it's the same as original or if the key is 'selected'
                            _if ('selected' in json) {
                                console.log((json.selected));
                                if (json.selected.indexOf(key) > -1 || key === $.trim(original.revert)) {_
                                    $(option).prop('selected', 'selected');
                                }
                            }
