### ISSUE TITLE
Allow repeated attempt to save changes on error

### ISSUE THREAD

**Issue by feihtthief** [NicolasCARPi/jquery_jeditable#192]
# Description

If the edit form gets submitted, but the server responds with a non-success code, the form should stay open and it should be possible to re-submit. Currently the res-submission is blocked because isSubmitting stays true after the ajax call completes, thereby preventing further save attempts. Cancelling would result in the users changes getting lost.

## How to reproduce

https://jsfiddle.net/feihtthief/az9k2jh0/3/

## Expected result

Repeated attempts to save the data should be allowed if the first one fails.

## Actual result

Only the first attempt to save gets submitted to the server. The others are blocked because isSubmitting  is still true

# Environment

jQuery version:  3.3.1
Browser: Chrome
OS: Windows

# Potential fix 

Add the following to the defaults for ajaxoptions 

```
complete: function (xhr, status) {
    isSubmitting = false;
}
```

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for reporting this issue and providing a possible fix. I'll have a more thorough look asap.

**Comment by NicolasCARPi** [comment]
Changed added ;)
