### ISSUE TITLE
How to set the id of input field

### ISSUE THREAD

**Issue by sseppo** [NicolasCARPi/jquery_jeditable#195]
# Description
Script puts it's own id as the id of the input-text field. But it would be more useful if one could set their own id there, for i.e. purpose to update result to database (thus, along the text would be needed the id it refers to). If this is possible already, I did not find a way to do it. I only can set the name of the id field sent, but not the content of the id-field.  ##

**Comment by NicolasCARPi** [comment]
>  I only can set the name of the id field sent, but not the content of the id-field

That's the spirit. The id will be the id, even if you can change the name. But if you need to send along more data (a very common practice with jquery-jeditable), it's very easy to do so with [submitdata](https://jeditable.elabftw.net/api/#jquery-jeditable).
