### ISSUE TITLE
dynamic autocomplete with a huge list

### ISSUE THREAD

**Issue by anonymous-explorer** [NicolasCARPi/jquery_jeditable#196]
# Description
I am trying to use jeditable as a table inplace editor and need to have a suggestions list to be updated dynamically as the user is typing (the same way as typeahead.js or "ajax live search" from ajaxlivesearch.com. My list is a huge, about 10K items in the form of ID and value pairs stored in the database, I need to choose ID while searching for value. This list is static. Could someone give a hint of how make it?

**Comment by NicolasCARPi** [comment]
You might want to use this: https://jqueryui.com/autocomplete/

Also, don't load the full 10k but wait at least 3 char typed to load only the matched ones.

Closing this issue as it's not pertinent to jquery-jeditable.
