### ISSUE TITLE
How to format selected Date in datepicker

### ISSUE THREAD

**Issue by Telefisch** [NicolasCARPi/jquery_jeditable#197]
I just tried out the datepicker-example and formated the shown Date with "dateFormat: dd.mm.yyy".
If I select a date, the following string is returned:

Tue Mar 05 2019 00:00:00 GMT+0100 (Mitteleuropäische Zeit)

what did I wrong?

jQuery version: 3.3.1
Browser: Edge
OS: Win 10 pro

**Comment by NicolasCARPi** [comment]
Does it work with "dd-mm-yy" as shown in the [demo](https://jeditable.elabftw.net/)?

**Comment by Telefisch** [comment]
...funny...
yesterday I deleted the Format Setting for testing.
Today, I added it again and it works like expected, with both Formats (dd-mm-yy and dd.mm.yy)
Thanks so far!

**Comment by NicolasCARPi** [comment]
Ok great :)
