### ISSUE TITLE
Allow repeated attempts to save changes when submit and onsubmit return false 

### ISSUE THREAD

**Issue by RobdeT** [NicolasCARPi/jquery_jeditable#199]
This is a similar problem to #192 but also occurs if the `onsubmit` or `submit` event functions return `false`. This does not allow these functions to be used for input validation.

This is also a problem if the user defined `target` function performs validation or might fail and need retries, for example if the function made an ajax call which failed. The current `responseHandler` does not support an error return that could reset the `isSubmitted` status.

The following solutions seem to solve this problem::

For the `onsubmit` and `submit` functions set `isSubmitting` based on return value and continue if `isSubmitting` is still `true.

For the `target` function, always  set `isSubmitting` to `false` when the `responseHandler` is called and if the function returns `false` do not update the DOM but set `isSubmitting` to `false`. To allow the `target` function to complete without updating the DOM, to allow retries, and to avoid a breaking change to existing `target` functions that might use `false` as a way to clear the DOM, change the signature of the `responseHandler` to add a `complete` parameter to stop the update of the DOM if it is set to `false`. Existing code will not pass this parameter so exiting behaviour will be maintained.

```
359                    /* Call before submit hook. */
360                    /* If it returns false abort submitting. */
                       isSubmitting = false !== onsubmit.apply(form, [settings, self]);
361                    if (isSubmitting) {
362                        /* Custom inputs call before submit hook. */
363                        /* If it returns false abort submitting. */
                            isSubmitting = false !== submit.apply(form, [settings, self]);
364                        if (isSubmitting) {
365
366                          /* Check if given target is function */
367                          if ($.isFunction(settings.target)) {
368                             /* Callback function to handle the target reponse */
369                              var responseHandler = function(value, complete) {
                                     isSubmitting = false;
                                     if (false !== complete) {
370                                      $(self).html(value);
371                                      self.editing = false;
372                                      callback.apply(self, [self.innerHTML, settings]);
373                                      if (!$.trim($(self).html())) {
374                                          $(self).html(settings.placeholder);
375                                      }
                                     }
376                              };
377                              /* Call the user target function */
378                              var userTarget = settings.target.apply(self, [input.val(), settings, responseHandler]);
379                              /* Handle the target function return for compatibility */
380                              if (undefined !== userTarget) {
381                                  responseHandler(userTarget, userTarget);
382                              }
383
```

**Comment by NicolasCARPi** [comment]
Hello @RobdeT,

Thank you for your report. Do you think it would be possible for you to create a pull request for this issue?

See: https://github.com/NicolasCARPi/jquery_jeditable/blob/master/CONTRIBUTING.md

~Nico

**Comment by NicolasCARPi** [comment]
ping @RobdeT
