### ISSUE TITLE
How to submit on mouse out

### ISSUE THREAD

**Issue by dhruti3011** [NicolasCARPi/jquery_jeditable#200]
I have jeditable datatable.
I do not want the data to be saved onblur. What my implementation is that I have a "Save" button(outside of my table) which takes the values and then saves the values in the database.
I do not want the "OK" button, hence I have the code "submit": ""
What is happening is that I have to either press enter or click outside of my table to retain the values.
What I require is that when I click "Save" button, onblur should be called so that the values are retained(or some other mechanism to retain the data on click of the button), which is not happening.
salesDataTbl.$(edit).editable(theCallback, {
tooltip: 'Click to edit and press enter',
"callback": function (sValue, y) {

},
"submit": "",
"onblur": 'submit',
});

**Comment by NicolasCARPi** [comment]
Hello,

Why don't you use [blur()](https://api.jquery.com/blur/) on your table when the external save button is clicked?

**Comment by dhruti3011** [comment]
Hello,
I did try, but in vain.
Is there another way?
Regards,
Dhruti

**Comment by NicolasCARPi** [comment]
It would help greatly if you could provide an example of your code running. I created a template to help with the process: https://codepen.io/pen?template=pBxBXm

**Comment by dhruti3011** [comment]
Hello Nicolas,

Thank you for your quick response.
I've saved the code: https://codepen.io/anon/pen/rbqEzJ
It works in my local. Except that the rows are got from the database.
Please let me know if you need any other details.

**Comment by NicolasCARPi** [comment]
You forgot to add jquery-datatable (in Settings -> javascript) in your example.

I do not see your Save button. Also note that onblur can be a function ([see doc](https://jeditable.elabftw.net/api/#jquery-jeditable)):

~~~javascript
onblur: function() { return false }
// or
onblur: 'cancel'
~~~

Is this what you want?

**Comment by dhruti3011** [comment]
Hi,
The below code is not working.

onblur: function() { return false }// or
onblur: 'cancel'

What I'm trying to do is, have onblur: submit.

And then when I click on save, ideally the onblur of datatable td
method should be called first(as the focus is on the button now).

However, what is happening is it is calling the submit button, and at
this point the new edited value is not reflected because the blur is
not called.

**Comment by NicolasCARPi** [comment]
Did you try with "onsubmit"? It is called before submit.

**Comment by dhruti3011** [comment]
Hello ,

I found a work around for this.
Thank you very much for your prompt support! :)

Regards,
Dhruti
