### ISSUE TITLE
Select field not working on Firefox

### ISSUE THREAD

**Issue by RepoCorp** [NicolasCARPi/jquery_jeditable#202]
# Description
I have a `td` element configured as an editable select input that makes a request to get the dropdown values. It works as expected on Chrome but doesn't on Firefox. In Firefox I see it makes the request and gets the right values, but the dropdown only shows the first one and seems to freeze. It doesn't let me see other values and it doesn't react to losing focus.

```
        $(this).editable('example.com',{
          loadurl : '/example/choices_get.json',
          type   : 'select',
          indicator:	'Saving...',
          tooltip	:	'Click to edit...',
          event: 'focus',
          onblur: 'submit'
        })
```

jQuery version: 1.9.1
Browser: Works on Chrome, doesn't work on Firefox
OS: Various

**Comment by NicolasCARPi** [comment]
Do you see any error in the console? What if you remove the `event` option?

**Comment by RepoCorp** [comment]
In the console I only see a migration warning
```
jquery-migrate-1.4.1.js?1560789405:45 JQMIGRATE: jQuery.fn.attr('selected') might use property instead of attribute
```

I removed the event option and still didn't work. I tried removing other attributes from the configuration and from the element and it seems that the issue is caused by the attribute `contenteditable` in the `td` element. I need that attribute for accessibility purposes to be able to get to the element without a mouse.

**Comment by NicolasCARPi** [comment]
I cannot reproduce your issue. See https://codepen.io/nicolascarpi/pen/ewWpzr

Try to get a reproducible case in the codepen editor.

**Comment by RepoCorp** [comment]
Thank you very much @NicolasCARPi for your help and sorry for my late response. 

I reproduced it here https://codepen.io/catalina-de-la-cuesta/pen/PrxjZd.

But looking for the problem I found out it's a Firefox issue, not directly related to jeditable. In the pen I added two simple selects with and without `contenteditable` and in Firefox the one with `contenteditable` doesn't work 😒.

**Comment by NicolasCARPi** [comment]
Yes, I can confirm it doesn't work with me with firefox either.

**Comment by RepoCorp** [comment]
I guess there's nothing we can do about it then 😩.

Thank you very much for your help.
