### ISSUE TITLE
Error using plugin with Drupal 8 

### ISSUE THREAD

**Issue by francesco-pesenti** [NicolasCARPi/jquery_jeditable#205]
Hi, I'm using this great lib in a Drupal 8 project; all works fine except when I'm using a plugin (eg. datepicker).
Since Drupal uses jQuery in a no-conflict mode other scripts need to be wrapped with:
```
(function($) {
})(jQuery);
```

From official documentation (https://www.drupal.org/docs/8/api/javascript-api/javascript-api-overview):

> Note: Since Drupal uses jQuery.noConflict() and only loads JavaScript files when required, to use jQuery and the $ shortcode for jQuery you must include jQuery and Drupal as dependencies in the library definition in your MODULE.libraries.yml and add a wrapper around your function.

I saw you wrap the main script but not the plugins. Are there some issues on do this? 
If no and you agree I can made a patch.

**Comment by NicolasCARPi** [comment]
Hello,

Indeed the plugins are not wrapped, a patch would be much appreciated! :)

**Comment by francesco-pesenti** [comment]
https://github.com/NicolasCARPi/jquery_jeditable/pull/207
