### ISSUE TITLE
self.editing out of sync

### ISSUE THREAD

**Issue by keturn** [NicolasCARPi/jquery_jeditable#21]
I'm looking at a case where I'm using jeditable with datatables, and if the datatable row gets updated when I'm editing something in that row, the input form goes away but the "editing" attribute on the node is left set to true.  Then next time I click on the cell to edit it, it hits the "if (self.editing)" case, and skips out.

So self.editing should be unset at some point where it isn't.  I'm not quite sure where the right place to add that hook is.  At the moment I'm binding to "DOMNodeRemoved" on the editable form node.

**Comment by NicolasCARPi** [comment]
Hello, please provide example case on jsfiddle/codepen.
