### ISSUE TITLE
$('.edit').editable() doesnt work in Partial View in ASP.NET MVC5

### ISSUE THREAD

**Issue by yizongk** [NicolasCARPi/jquery_jeditable#210]
# Description
in ASP.NET
When you attempt to use Ajax to load in partial views, any element with \<div class='edit'\> in the partial view is not able to be editable.

## How to reproduce
Use Visual Studio and generate a general MVC 5 application, and in it's Home/Index, add a div for your partial view to be loaded into. Create a partial view, and use Ajax to load the partial view into Home/Index (Will provide some codes when I get the time)

It helps a lot if you can create a working example from this template:
https://codepen.io/pen?template=pBxBXm   (Will try this when I get home)

## Expected result
Be able to edit the div with a single click
## Actual result
Nothing happens, jeditable doesn't work
# Environment

jQuery version: 3.4.1
Browser: Firefox Dev version 71.0b4 (64-bit)
OS: Wins 10

**Comment by NicolasCARPi** [comment]
I'll let you update your issue with a codepen example ;)

**Comment by NicolasCARPi** [comment]
Yes, it is an issue with this library, element needs to exist. For dynamic elements, I just call it again on it and it works.

Thanks for posting the detailed explanation, I'm sure it'll help someone somewhere... :)
