### ISSUE TITLE
jQuery Migrate plugin warnings

### ISSUE THREAD

**Issue by gabrielweyer** [NicolasCARPi/jquery_jeditable#211]
# Description

I'm using the [jQuery Migrate](https://github.com/jquery/jquery-migrate/) plugin to be able to migrate to `jQuery 3.4.1` over time. This plugin displays warnings in the console for `jQuery` features that have been and will be removed.

`jquery-jeditable` is using some features that will be deprecated:

- `bind`
- `unbind`
- `click`
- `focus`
- `keydown`
- `submit`

The solutions to address the warnings are listed at [jQuery Migrate Plugin - Warning Messages](https://github.com/jquery/jquery-migrate/blob/master/warnings.md).

## How to reproduce

The below pen exhibits the issue:

https://codepen.io/gabrielweyer/pen/vYEYQYR

## Expected result

No warnings are displayed by `jQuery Migrate`.

## Actual result

**Note**: I'm running against `jquery-jeditable 2.0.13` unminified.

Warnings are displayed by `jQuery Migrate`.

![image](https://user-images.githubusercontent.com/2101647/70014495-13091f80-15cf-11ea-8103-c725fa24a715.png)

![image](https://user-images.githubusercontent.com/2101647/70014393-bf96d180-15ce-11ea-88e2-59647c6580c0.png)

# Environment

`jQuery` version: `3.4.1`
Browser: Chrome version `78.0.3904.108` (Official Build) (`64-bit`)
OS: Windows `10` fully patched

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for reporting this issue.

`jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos` and `jQuery.expr.filters is deprecated; use jQuery.expr.pseudos` are coming from jquery-ui and it's already the latest version.

I could resolve the bind issue and two click, but don't know why this one is still showing:
`jQuery.fn.click() event shorthand is deprecated`...

**Comment by gabrielweyer** [comment]
The fix for the `click` looks good to me.

- You can replace `unbind` by `off`
- `.focus()` can be replaced by `.trigger('focus')`
- `.keydown(function(e)` can be replaced by `.on('keydown', function(e)`
- `.submit()` can be replaced by `.trigger('submit')`
- `.submit(function(e)` can be replaced by `.on('submit', function(e)`

**Comment by NicolasCARPi** [comment]
I've just pushed a commit with those changes.

**Comment by gabrielweyer** [comment]
Thank you. I tested the changes and can confirm the migration warnings are gone.

**Comment by NicolasCARPi** [comment]
ok I'll publish a patch then.

**Comment by gabrielweyer** [comment]
Thank you for addressing this promptly 👍 .

**Comment by JamoCA** [comment]
I'm using v2.0.14 and notice JQMigrate warnings regarding the deprecated `blur()` event after clicking on an element to edit.

`JQMIGRATE: jQuery.fn.blur() event shorthand is deprecated`

**Comment by NicolasCARPi** [comment]
@JamoCA Thanks for the report. I have pushed a change on the `experimental` branch. Could you please try it out?

**Comment by JamoCA** [comment]
This update appears to be good.  I didn't receive any console warnings and the editing was cancelled when the focus was lost.

**Comment by NicolasCARPi** [comment]
Ok, a new version has been released with this patch.
