### ISSUE TITLE
How to manage callback results? 

### ISSUE THREAD

**Issue by ottopic** [NicolasCARPi/jquery_jeditable#213]
Hello,
I have tried to manage server side's result to show to user alert popup if error occurred.
Problem is that my callback json result is replaced into edited text field.

Is there a workaround to do this? 

Best regards

**Comment by NicolasCARPi** [comment]
Hello,

Did you look at the complete example from https://jeditable.elabftw.net/ ? There is a callback example:

![2020-02-04-131411_459x120_scrot](https://user-images.githubusercontent.com/3043706/73744047-417eb480-4750-11ea-9f38-0ffae8f8e641.png)

**Comment by ottopic** [comment]
Yes sure, but variable result is put by default inside edited text field value.
So, in 'result' if I return form server side script a json like {success: false, error: 'wrong data'} I can't prevent it replace original edited text.

**Comment by NicolasCARPi** [comment]
Then you might want to use the `intercept`. There is code for it on the demo page a bit lower.

**Comment by ottopic** [comment]
Yes, it is. Thank you. Intercept is not mentioned inside documentation and API sections.

Best regards

**Comment by NicolasCARPi** [comment]
> Intercept is not mentioned inside documentation and API sections

Correct! I'll add it.
