### ISSUE TITLE
Jeditable and Webgrid Sorting/Paging

### ISSUE THREAD

**Issue by jhuynh613** [NicolasCARPi/jquery_jeditable#219]
Has anyone tried using this with webgrid? If you do not use the paging or sorting function in webgrid everything works fine but if you click to sort or page all the in place edit do not work/disappear. There is no errors, nothing happens after a click. How does someone get around this or is this a bug? Thanks!

**Comment by NicolasCARPi** [comment]
You'll want to attach the listener to an element that doesn't get reloaded, or reattach the listener after that action.

**Comment by jhuynh613** [comment]
Thanks Nicolas, that did the trick.
