### ISSUE TITLE
Submitting multiple different Values when submit button is clicked

### ISSUE THREAD

**Issue by Chris-Pyro** [NicolasCARPi/jquery_jeditable#222]
# Description
Hey, I have a huge Table that has editable cells. what i want to do is have the changed values updated or inserted into my database when the user clicks a button. I cant get it to work. I do have a SQL query for inserting new values to the given ids but i can't figure out how to do it from the table.

I need to somehow set the cell ids and values and then get them in a form i can send to the DB also I have to look into creating new rows because my table is able to add a new row to it self but i dont know how to also add that to the DB.

Any advice would be greatly appreciated, as i cant seem to find any good help on the web.

**Comment by NicolasCARPi** [comment]
Hello,

Looking at the examples on [this page](https://jeditable.elabftw.net/) is a good start.

**Comment by Chris-Pyro** [comment]
Hey, thanks for the reply, 
I did already look at the Demo. The table works and it echos the changes into the given cell. Just as in the Demo.
The Problem I encounter is that I have no idea how to change the save.php to send the value to my database. i tried changing the "echo $_POST['value']" to a query to post it to the database and that works if i use "UPDATE table SET index='ABC' WHERE ID=1;" but doesnt if I use "UPDATE table SET index=$_POST['value'] WHERE id=1;"
