### ISSUE TITLE
not getting data from submitdata in jeditable

### ISSUE THREAD

**Issue by Danish-Ali097** [NicolasCARPi/jquery_jeditable#227]
# Description
i'm not being able to get **submitdata** data
## How to reproduce

It helps a lot if you can create a working example from this template:
(https://codepen.io/danish-ali097/pen/vYyYGYw?editors=0011)

## Expected result
i should be getting {"row_id":1, ["column":4]}
## Actual result

# Environment

jQuery version: 3.xx
Browser:
OS:

**Comment by NicolasCARPi** [comment]
Hello, did you manage to address this issue?

I'm sorry I can't provide free support for this library.
