### ISSUE TITLE
jeditable destroys user tooltips

### ISSUE THREAD

**Issue by sronsiek** [NicolasCARPi/jquery_jeditable#241]
# Description
jeditable version:  2.0.19

My data contains (valuable)  tooltip info which is passed from the server.

To prevent jeditable from overwriting this (default set within jeditable = '_Click to edit_'), I need to set the tooltip option to `null` or `false`.

But following an edit, my tooltips have disappeared.

Cause is a missing check before overwriting the tooltip at the end of in `form.on('submit', function(e)`:

Changing this:
```
                    /* Show tooltip again. */
                    $(self).attr('title', settings.tooltip);
                    return false;
```

to:

```
                    /* Show tooltip again. */
                    if (settings.tooltip) {
                       $(self).attr('title', settings.tooltip);
                    }
                    return false;
```

fixes the issue.

Comment: I would think it more intuitive if there was no default set - so if the user
does not set a value, jeditable should not interfere with this attribute. 

This was the behaviour in 1.7.3.

**Comment by NicolasCARPi** [comment]
>  I would think it more intuitive if there was no default set - so if the user
does not set a value, jeditable should not interfere with this attribute.

I agree, but I won't make breaking changes now.

I have commited your proposed change!

**Comment by sronsiek** [comment]
Great, thanks. Some more suggestions in the pipeline ... I'll be back ;)
