### ISSUE TITLE
Using JSON to fill a dropdown selection

### ISSUE THREAD

**Issue by kkaiser1952** [NicolasCARPi/jquery_jeditable#246]
I’d like the return from the MySQL in the <td below, the call is in the jQuery below that and PHP below that. But nothing ever shows up as a dropdown on the page. There should be 4 items, BIKES, CARS, PLANES, TRAINES. The field clears as it should but no dropdown appears, where did I go wrong?

~~~javascript
        <td $timeline $brbCols $badCols 
            class=\"editable editfacility c33 \"	
            id=\"facility:$row[recordID]\"      
            onClick=\"empty('facility:$row[recordID]');\"> 
                <div class='$class'> $row[facility] </div>	       
        </td>

	// with JSON feed
         $(".editfacility").editable("save.php", {
            type   : "select",
            loadurl : "GetListOfFacilities.php",
            submit : "OK",
            style  : "inherit"
         });
~~~

~~~php

<?php
// This query gets and formats the selection criteria for the facility column 

require_once "dbConnectDtls.php";


	$q = $_POST['q'];
	//echo $q;
	$q = 'MYOWN';  
	    
	$sql = "SELECT facility
			  FROM `facility`
			 WHERE groupcall = '$q'
		   ";
	
        	$listarray = array();
	  	foreach($db_found->query($sql) as $row) {
		    $listarray[] = $row;
	  	} // end foreach
		    
		   //write to json file
       		    $fp = fopen('empdata.json', 'w');
            	    fwrite($fp, json_encode($list));
                    fclose($fp);
?>
~~~

The output looks like this;

~~~json
[{"facility":"CARS and Trucks","0":"CARS and Trucks"},{"facility":"PLANES including Private","0":"PLANES including Private"},{"facility":"TRAINS including Subways","0":"TRAINS including Subways"},{"facility":"BIKE And Motorcycles","0":"BIKE And Motorcycles"}]
~~~

**Comment by NicolasCARPi** [comment]
Hello,

This is what your json should look like:

~~~json
{"D":"Letter D","E":"Letter E","F":"Letter F","G":"Letter G","selected":"selected one"}
~~~

(from https://jeditable.elabftw.net/json.php)

Here yours is in an array and doesn't have the same structure.

Please note that this library is deprecated and I'm currently focusing on https://github.com/deltablot/malle/.

**Comment by kkaiser1952** [comment]
Two questions if I may.
One: I thought I was using a prescribed method to change the output of my MySQL into JSON. I see now it didn't do the job. Should I just manually output the data in that format instead?
Two: I use jQuery in so many places I my C.R.U.D. app would there be a reasonable reason to switch to Malle?

**Comment by NicolasCARPi** [comment]
1. You should just take the first element of the array and it should encode fine in json.
2. No reasonable reason for you to switch, no.

**Comment by kkaiser1952** [comment]
Thanks for that info both 1 and 2.
The output of MySQL now looks like this; 

{"CARS and Trucks":"CARS and Trucks","PLANES including Private":"PLANES including Private","TRAINS including Subways":"TRAINS including Subways","BIKE And Motorcycles":"BIKE And Motorcycles",}

Which I do in php as;  echo "$list"; but I'm missing the mechanism to move that data back to the <td> for the dropdown. The example (thanks by the way) doesn't spell it out for me.

**Comment by kkaiser1952** [comment]
I'm missing the mechanism to move that data back to the for the dropdown. The example (thanks by the way) doesn't spell it out for me.

**Comment by kkaiser1952** [comment]
Never mind. I figured it out after many hours of trial and error I had a capital letter where I didn't want it. OH MAN!
