### ISSUE TITLE
Add support for onEditCallback function

### ISSUE THREAD

**Issue by Toub** [NicolasCARPi/jquery_jeditable#28]
It is currently not possible to extend the edition mechanism (for example to modify other elements of the page when editing: hide the images, put the rest of the page in grey...)

It is simple to add an onEditCallback parameter called just after that the edit form is displayed (based on the callback model):
- @param Function options[onEditCallback] Function to run before editing the content **
  [...]  
  var onEditCallback = settings.onEditCallback || function() { };
  [...]
  onEditCallback.apply(self, [self.innerHTML, settings]);

**Comment by NicolasCARPi** [comment]
Hello, you can use onedit or before to do that.
