### ISSUE TITLE
Move the "onedit" event to a point after the form has been loaded, and is (really) ready for editing

### ISSUE THREAD

**Issue by MrBertie** [NicolasCARPi/jquery_jeditable#35]
Moving this event would allow plugin users to bind keypress events, for example to map _ctrl+return_, or similar, to the (newly created) submit button.
I patched the plugin to try this out and it works well in combination with the _jquery.hotkeys_ plugin.

**Comment by NicolasCARPi** [comment]
Hello,

Please provide patch and example case :)

Regards,
~Nico
