### ISSUE TITLE
jEditable Custom Form submit

### ISSUE THREAD

**Issue by pviral** [NicolasCARPi/jquery_jeditable#47]
I am using jeditable to edit form and stuck at custom form submit to server.

There is product description box I need to edit. when some click edit it pops-up a window with product description in editable mode with a extra drop-down box (asking for reason what is user changing). However, I need only description to display on webpage but not reason.

How can I do this?

Example code

<pre>
<code>
$.editable.addInputType('autogrow', {
 element : function(settings, original) {
 var hourselect = $('<select id="reason" name="reason">');
 var textarea = $('<textarea id="text" />');
 $(hourselect).append(
 $('<option />').text('Select a reason').val(''),
    $('<option />').text('Adding new Description').val('1'),
    $('<option />').text('Editing Grammar').val('2')
  );
 $(this).append(hourselect);

 if (settings.rows) {
  textarea.attr('rows', settings.rows);
  } else {
  textarea.height(settings.height);
  }
  if (settings.cols) {
   textarea.attr('cols', settings.cols);
  } else {
  textarea.width(settings.width);
  }
    $(this).append(textarea);
    /* Last create an hidden input. This is returned to plugin. It will */
    /* later hold the actual value which will be submitted to server.   */
   var hidden = $('<input type="hidden" />');
    $(this).append(hidden);

    return(hidden);
},
plugin : function(settings, original) {
    $('textarea', this).autogrow(settings.autogrow);
},
submit: function (settings, original) {
var value = $('#text').val();
    $('input', this).val(value);
 }
});

</code>
</pre>

I can only send one value to server i.e. text or reason  using hidden input field. However, I want to send reason and update description to server.

Has anybody came across this problem or use-case and provide some guidance?

I was using timepicker as my example.

Viral

**Comment by NicolasCARPi** [comment]
Hello,

See https://github.com/NicolasCARPi/jquery_jeditable/pull/109. It'll let you do what you want.
