### ISSUE TITLE
Text Input

### ISSUE THREAD

**Issue by lstebner** [NicolasCARPi/jquery_jeditable#49]
This is more of a suggestion than an issue, but the default input when passing 'text' does not have a 'type' property on it, see:
text: {
                element : function(settings, original) {
                    var input = $('<input />');

My suggestion is to alter this to:
text: {
                element : function(settings, original) {
                    var input = $('<input type="text" />');

My reasoning is: 
1. I don't think the <input> tag is valid without the "type" attribute
2. (and actually more important to me) Having the type makes the field easier to custom style plus it will then automatically inherit all of my "input[type='text']" styles that already exist.

**Comment by NicolasCARPi** [comment]
Hello,

I'm the new maintainer of this project.

This issue is now fixed :)

Regards,
~Nico
