### ISSUE TITLE
Add class to editable item

### ISSUE THREAD

**Issue by jk3us** [NicolasCARPi/jquery_jeditable#55]
It would be nice to add a classname (perhaps as a param) to the item that becomes editable.  I'm adding this to individual elements using #id selectors, and would rather have editable add a class name to these so I can style them with css (or even addition javascript pizazz).  I thought that's what the cssclass param does, but that doesn't seem to be the case.

**Comment by NicolasCARPi** [comment]
You can use `cssclass` for that. See https://github.com/NicolasCARPi/jquery_jeditable/blob/master/demos/index.html#L159
