### ISSUE TITLE
Tabbing from input to submit button fails

### ISSUE THREAD

**Issue by jisotupa** [NicolasCARPi/jquery_jeditable#63]
Given the following the following conditions are met:
- you are using "submit", "cancel" or a function for onblur option
- you have defined "submit" and/or "cancel" buttons

When you navigate with the TAB key from the input element to either of the buttons, the input element is blurred and the "onblur" option is triggered although from the user's point of view the focus is not lost from the editable input.

So if you want to navigate to OK button using a tab key', you lose any changes you have made.

I think the onblur should be triggered only after the focus is in none of the controls: the input, the submit button or the cancel button.

**Comment by NicolasCARPi** [comment]
Hello,

Thanks for reporting this bug. If the onblur function returns true, the behavior will be as expected, so I'm closing this. :)
