### ISSUE TITLE
Problem with CKEditor integration

### ISSUE THREAD

**Issue by Quadratica** [NicolasCARPi/jquery_jeditable#82]
Can i ask here how can i integrate jEditable and CKEditor ?
I've tried with no complete success.

Thank you

**Comment by endrezalan** [comment]
Hello. Unfortunately the links provied are old and not working. If it is possible can you provide some documentation ?

**Comment by NicolasCARPi** [comment]
@endrezalan did you have a look there: https://stackoverflow.com/questions/5474503/how-to-use-config-with-ckeditor-and-jeditable/9581722 ?
