### ISSUE TITLE
I get html only as return for Value?

### ISSUE THREAD

**Issue by ghost** [NicolasCARPi/jquery_jeditable#90]
To clear things up first:
Im pretty new to jQuery!

whenever I try to edit a field and send its value to my save.php file, jeditable automatically comments my php code with HTML "<-- .... -->" so Iam not able to write php to work with the value.

Example when I have my field and send it to the OPs originally used save.php, my new value in the textarea is (see pictures)

$(document).ready(function() {
                $('.edit_area').editable('save.php', {
                    id   : 'elementid',
                    name : 'newvalue',
                    type : 'textarea',
                    cancel : 'Cancel',
                    submit : 'OK',
                    tooltip : 'Click to edit...',
                    indicator : 'Saving...',
                    onblur: 'ignore',
                });
            });

Thats my box.
Please help need it asap for my exam :D
![Unbenannt](https://f.cloud.github.com/assets/4164539/383090/cd30c89e-a60b-11e2-94e2-e539f74f6e53.JPG)
![Unbenannt2](https://f.cloud.github.com/assets/4164539/383092/d16318a4-a60b-11e2-9d75-9ce2cacabfb5.JPG)

**Comment by NicolasCARPi** [comment]
You're not interpreting PHP. Use a local browser for the demo ;)
