### ISSUE TITLE
Width correction bug

### ISSUE THREAD

**Issue by FredFrin** [NicolasCARPi/jquery_jeditable#93]
I've been running this great plugin without ajax requests, though I think the bug would be there with ajax too. I set width = 100 and edit a text field - all is fine. I click on the background to cancel the edit. The second time I edit any text field, the text field width has shrunk to it's autowidth value. 

Looking at the code I saw there is a correction for loss of width size on the html anchor element following edit:

```
        /* inlined block elements lose their width and height after first edit */
        /* save them for later use as workaround */
        var savedwidth  = $(self).width();
        var savedheight = $(self).height();




            /* figure out how wide and tall we are, saved width and height */
            /* are workaround for http://dev.jquery.com/ticket/2190 */
            if (0 == $(self).width()) {
                //$(self).css('visibility', 'hidden');
                settings.width  = savedwidth;
                settings.height = savedheight;
```

In the last 2 lines we overwrite the settings width with the anchor width. This is where we lose the original setting - if one was used. I would have thought the code should be:

```
               $(self).width( savedwidth )
               $(self).height( savedheight )
```

But this does not work. I have made the following change - which works for me:

```
                settings.width  = (settings.width  != 'none' && settings.width  > savedwidth)  ? settings.width  : savedwidth;
                settings.height = (settings.height != 'none' && settings.height > savedheight) ? settings.height : savedheight;
```

I'm not claiming this to be the correct solution - but there is definitely need for correction here!

**Comment by NicolasCARPi** [comment]
Hello,

Width/height should work better now :)
