### ISSUE TITLE
Applying to hidden element takes 10-times more time

### ISSUE THREAD

**Issue by divinoro** [NicolasCARPi/jquery_jeditable#98]
Hi, I just found a bit strange bahavior of the plugin.

How to reproduce:
- generate table with some set of TDs with style set to display:none
- apply Jeditable to the class, which is attached to each of these TDs

Firebug profiling is showing approx. 10-time performance decrease in that case.

I haven't profile in Chrome, but page load is also delayed by long time.

Observed on both Linux & Windows.

Cheers,
Ivan

**Comment by NicolasCARPi** [comment]
Hello,

Thanks for the report. Please provide a proper test case if this behavior is still observable.

~Nico
